namespace DarkStore.Domain.Orders;

/// <summary>
/// Order — stored in Azure SQL (AppDbContext).
///
/// FIX 1.2: No AddressId FK to KZ Local DB. Instead, address fields are snapshotted
/// into the Order row at creation time. This prevents cross-DB FK violations and
/// preserves the delivery address even if the user later edits their address book.
///
/// FIX 1.4: OrderNumber is generated via SQL Server SEQUENCE "OrderNumberSeq" — format
/// DS-{year}-{seq:D6} — configured in OrderConfiguration. UNIQUE INDEX enforced.
/// Never use Random.Next() — collision risk at concurrent load.
/// </summary>
public class Order : Common.BaseEntity
{
    private Order() { } // EF Core

    // ── Identification ──────────────────────────────────────────────────────
    /// <summary>
    /// Human-readable order number. Generated by SQL Server SEQUENCE (not Random.Next).
    /// Format: DS-2026-000001. UNIQUE INDEX in DB. Set by HasDefaultValueSql in EF config.
    /// </summary>
    public string OrderNumber { get; private set; } = string.Empty;

    /// <summary>Logical FK to Users in KZ Local DB. Only the GUID crosses databases.</summary>
    public Guid UserId { get; private set; }

    // ── Address snapshot (FIX 1.2) ──────────────────────────────────────────
    // These fields are populated from the Addresses record in KZ Local DB at order creation.
    // After that moment they are immutable — they reflect the address AS IT WAS when ordered.
    // There is NO AddressId FK column.

    public string DeliveryStreet { get; private set; } = string.Empty;
    public string DeliveryBuilding { get; private set; } = string.Empty;
    public string? DeliveryApartment { get; private set; }
    public decimal DeliveryLatitude { get; private set; }
    public decimal DeliveryLongitude { get; private set; }
    /// <summary>Full human-readable label, e.g. "ул. Сатпаева, 7, кв. 12".</summary>
    public string DeliveryDisplayLabel { get; private set; } = string.Empty;

    // ── Status & amounts ────────────────────────────────────────────────────
    public OrderStatus Status { get; private set; }
    public decimal TotalAmount { get; private set; }
    public decimal CalculatedDeliveryFee { get; private init; }
    public decimal ActualDeliveryFee { get; private set; }
    public int LoyaltyPointsUsed { get; private set; }

    public DateTimeOffset? EstimatedDelivery { get; private set; }
    public DateTimeOffset? ActualDeliveryAt { get; private set; }

    // ── Navigation ──────────────────────────────────────────────────────────
    public IReadOnlyCollection<OrderItem> Items => _items.AsReadOnly();
    private readonly List<OrderItem> _items = [];
    public Deliveries.Delivery? Delivery { get; private set; }

    // ── Factory ─────────────────────────────────────────────────────────────

    /// <param name="userId"></param>
    /// <param name="addressSnapshot">
    /// Address record fetched from KZ Local DB before calling this factory.
    /// Its fields are copied here — no reference to the KZ DB object is kept.
    /// </param>
    /// <param name="calculatedDeliveryFee"></param>
    /// <param name="createdBy"></param>
    public static Order Create(
        Guid userId,
        AddressSnapshot addressSnapshot,
        decimal calculatedDeliveryFee,
        string createdBy)
    {
        ArgumentNullException.ThrowIfNull(addressSnapshot);

        DateTimeOffset now = DateTimeOffset.UtcNow;
        return new Order
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            // Address snapshot — immutable copy at order creation time
            DeliveryStreet = addressSnapshot.Street,
            DeliveryBuilding = addressSnapshot.Building,
            DeliveryApartment = addressSnapshot.Apartment,
            DeliveryLatitude = addressSnapshot.Latitude,
            DeliveryLongitude = addressSnapshot.Longitude,
            DeliveryDisplayLabel = addressSnapshot.DisplayLabel,
            // OrderNumber left empty — filled by SQL SEQUENCE via HasDefaultValueSql
            Status = OrderStatus.Pending,
            CalculatedDeliveryFee = calculatedDeliveryFee,
            ActualDeliveryFee = calculatedDeliveryFee,
            TotalAmount = 0m,
            CreatedAt = now,
            UpdatedAt = now,
            CreatedBy = createdBy,
            UpdatedBy = createdBy
        };
    }

    public void AddItem(Guid productId, int quantity, decimal unitPrice, string updatedBy)
    {
        if (Status != OrderStatus.Pending)
        {
            throw new InvalidOperationException("Cannot add items to a non-pending order.");
        }

        var item = OrderItem.Create(Id, productId, quantity, unitPrice);
        _items.Add(item);
        TotalAmount += item.TotalPrice;
        ActualDeliveryFee = TotalAmount >= 10_000m ? 0m : CalculatedDeliveryFee;
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = updatedBy;
    }

    // ── Valid state transitions (state machine guard) ────────────────────────
    private static readonly IReadOnlyDictionary<OrderStatus, IReadOnlyCollection<OrderStatus>> _validTransitions =
        new Dictionary<OrderStatus, IReadOnlyCollection<OrderStatus>>
        {
            [OrderStatus.Pending]        = [OrderStatus.Confirmed, OrderStatus.Cancelled],
            [OrderStatus.Confirmed]      = [OrderStatus.Preparing, OrderStatus.Cancelled],
            [OrderStatus.Preparing]      = [OrderStatus.ReadyForPickup, OrderStatus.Cancelled],
            [OrderStatus.ReadyForPickup] = [OrderStatus.OnTheWay, OrderStatus.Cancelled],
            [OrderStatus.OnTheWay]       = [OrderStatus.Delivered, OrderStatus.Cancelled],
            [OrderStatus.Delivered]      = [],
            [OrderStatus.Cancelled]      = []
        };

    public void TransitionStatus(OrderStatus newStatus, string updatedBy)
    {
        if (!_validTransitions.TryGetValue(Status, out IReadOnlyCollection<OrderStatus>? allowed) || !allowed.Contains(newStatus))
        {
            throw new InvalidOperationException(
                $"Cannot transition order from {Status} to {newStatus}. " +
                $"Valid transitions: [{string.Join(", ", _validTransitions.GetValueOrDefault(Status) ?? [])}].");
        }

        Status = newStatus;
        if (newStatus == OrderStatus.Delivered)
        {
            ActualDeliveryAt = DateTimeOffset.UtcNow;
        }

        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = updatedBy;
    }

    public void ApplyLoyaltyDiscount(int points, string updatedBy)
    {
        LoyaltyPointsUsed = points;
        TotalAmount = Math.Max(0, TotalAmount - points);
        UpdatedAt = DateTimeOffset.UtcNow;
        UpdatedBy = updatedBy;
    }
}

public enum OrderStatus
{
    Pending = 0,
    Confirmed = 1,
    Preparing = 2,
    ReadyForPickup = 3,
    OnTheWay = 4,
    Delivered = 5,
    Cancelled = 6
}

